#!/usr/bin/env python3
"""Regenerate src/logo.rs from assets/logo/chloride-cli-lockup.svg.

Terminals cannot draw vectors, and shipping an SVG rasterizer would roughly
double a binary we deliberately keep small. So the logo is rendered here, at
development time, into two embedded forms:

* LOGO_COLOR — truecolor half-block art (each `▀` carries two pixels: the
  foreground colour is the top pixel, the background the bottom one).
* LOGO_PLAIN — monochrome braille art (2x4 pixels per char) for pipes,
  NO_COLOR, and terminals without truecolor.

Needs `rsvg-convert` and ImageMagick (`magick`) on PATH. Run from the repo
root:

    python3 scripts/logo-to-ansi.py
"""

import subprocess
import sys
from pathlib import Path

SVG = Path("assets/logo/chloride-cli-lockup.svg")
OUT = Path("src/logo.rs")
COLS = 58  # art width in terminal columns
ALPHA = 128  # opacity threshold: above this a pixel is part of the logo

# The four colours the SVG is drawn in. Every sampled pixel snaps to the
# nearest of these: downsampling otherwise blends the palette into muddy
# greys at terminal resolution, which is exactly how the logo should not look.
PALETTE = [
    (0x2B, 0x2B, 0x2B),  # charcoal
    (0x87, 0x98, 0x1E),  # olive
    (0xB7, 0xCB, 0x24),  # lime
    (0xFA, 0xF8, 0xF4),  # off-white
]


def snap(rgb):
    return min(PALETTE, key=lambda p: sum((a - b) ** 2 for a, b in zip(p, rgb)))


def run(args, stdin=None):
    return subprocess.run(args, input=stdin, capture_output=True, check=True).stdout


def rasterize(cols, rows_px_per_cell):
    """SVG -> exact (w, h, straight-alpha RGBA bytes) for a cols-wide grid."""
    png = run(["rsvg-convert", "-w", "1024", str(SVG)])
    # Trim transparent margins so the art fills the columns we give it.
    trimmed = run(["magick", "png:-", "-trim", "+repage", "png:-"], png)
    tw, th = map(int, run(["magick", "identify", "-format", "%w %h", "png:-"], trimmed).split())
    w = cols
    h = round(th / tw * cols) * rows_px_per_cell // rows_px_per_cell
    h = max(rows_px_per_cell, h - h % rows_px_per_cell)
    raw = run(
        ["magick", "png:-", "-resize", f"{w}x{h}!", "-depth", "8", "rgba:-"],
        trimmed,
    )
    return w, h, raw


def px(raw, w, x, y):
    i = (y * w + x) * 4
    r, g, b, a = raw[i : i + 4]
    return snap((r, g, b)) if a >= ALPHA else None


def color_art():
    """Half-block art: 1 pixel per column, 2 per row."""
    w, h, raw = rasterize(COLS, 2)
    lines = []
    for row in range(h // 2):
        fg = bg = "unset"
        line = []
        for x in range(w):
            top = px(raw, w, x, row * 2)
            bot = px(raw, w, x, row * 2 + 1)
            if top is None and bot is None:
                # Spaces paint the cell background, so it must be off.
                if bg != None:  # noqa: E711 — tri-state: None/"unset"/rgb
                    line.append("\\u{1b}[49m")
                    bg = None
                line.append(" ")
                continue
            ch = "▀" if top is not None else "▄"
            want_fg = top if top is not None else bot
            want_bg = bot if top is not None else None
            if want_fg != fg:
                line.append("\\u{{1b}}[38;2;{};{};{}m".format(*want_fg))
                fg = want_fg
            if want_bg != bg:
                if want_bg is None:
                    line.append("\\u{1b}[49m")
                else:
                    line.append("\\u{{1b}}[48;2;{};{};{}m".format(*want_bg))
                bg = want_bg
            line.append(ch)
        lines.append("".join(line).rstrip() + "\\u{1b}[0m")
    return lines


def plain_art():
    """Braille art: 2 pixels per column, 4 per row."""
    w, h, raw = rasterize(COLS * 2, 4)
    bits = [(0, 0, 0x01), (0, 1, 0x02), (0, 2, 0x04), (1, 0, 0x08),
            (1, 1, 0x10), (1, 2, 0x20), (0, 3, 0x40), (1, 3, 0x80)]
    lines = []
    for row in range(h // 4):
        line = []
        for col in range(w // 2):
            v = 0
            for dx, dy, bit in bits:
                if px(raw, w, col * 2 + dx, row * 4 + dy) is not None:
                    v |= bit
            line.append(chr(0x2800 + v) if v else " ")
        lines.append("".join(line).rstrip())
    return lines


def main():
    if not SVG.exists():
        sys.exit(f"run from the repo root: {SVG} not found")
    color = color_art()
    plain = plain_art()

    def const(name, doc, lines, escaped):
        body = "\n".join(
            '    "{}\\n",'.format(l if escaped else l.replace("\\", "\\\\").replace('"', '\\"'))
            for l in lines
        )
        return f"/// {doc}\npub const {name}: &str = concat!(\n{body}\n);\n"

    OUT.write_text(
        "//! The Chloride logo, pre-rendered to terminal art.\n"
        "//!\n"
        "//! GENERATED by scripts/logo-to-ansi.py from "
        "assets/logo/chloride-cli-lockup.svg — do not edit by hand.\n\n"
        + const(
            "LOGO_COLOR",
            "Truecolor half-block rendering; needs a colour terminal.",
            color,
            escaped=True,
        )
        + "\n"
        + const(
            "LOGO_PLAIN",
            "Monochrome braille rendering for pipes, NO_COLOR, and dumb terminals.",
            plain,
            escaped=False,
        )
    )
    print(f"wrote {OUT}: {len(color)} colour rows, {len(plain)} plain rows, {COLS} cols")


if __name__ == "__main__":
    main()
